version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout:
          submodules: true  # Ensure Emscripten submodule is cloned

      - run:
          name: Install dependencies
          command: |
            sudo apt update -y
            sudo apt install -y make g++ python3

      - run:
          name: Set up Emscripten
          command: |
            ./emsdk/emsdk install latest
            ./emsdk/emsdk activate latest

      - run:
          name: Build native debug
          command: make debug

      - run:
          name: Build web debug (WebAssembly)
          command: |
            source ./emsdk/emsdk_env.sh
            emmake make debug

      - run:
          name: Run tests with native release build
          command: python3 test.py ./bin/native/debug/word_count

workflows:
  version: 2
  build_and_test:
    jobs:
      - build